[package]
name = "oneway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "walk-dir"

[features]
default = []

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "io-util", "time", "fs"] }
nom = "7"
log = "0.4"
env_logger = "0.9"
